[package]
name = "hello_world"
version = "0.0.1"
authors = [ "Yama-Tomo <mazda13bturbo@gmail.com>" ]

[dependencies]
actix-web = "0.7"
diesel = { version = "1.4.2", features = ["sqlite"] }
dotenv = "0.13.0"
