version: '3.2'
services:
  backend:
    env_file:
      - .env
    image: yamatomo/vue-vuex-typescript-sample:ruby
    command: /bin/sh -c "bundle install && bundle exec rails db:migrate && bundle exec rake db:seed && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./__api:/app:cached

  puppeteer:
    env_file:
      - .env
    image: yamatomo/vue-vuex-typescript-sample:puppeteer
    volumes:
      - ./:/app:cached
      - /app/__api
    environment:
      IS_DOCKER: 'true'
      BROWSER_BIN_PATH: /usr/bin/chromium-browser
    command: /bin/sh -c "yarn --no-progress && yarn dev"
    depends_on:
      - backend

