version: '3.2'
services:
  puppeteer:
    environment:
      TEST_ARGS:
    command: /bin/sh -c "yarn --no-progress && yarn sb:build --quiet && ./docker/puppeteer/wait_for_backend.sh && yarn test $TEST_ARGS && yarn coverage"

