version: 2.1

references:
  node_runtime_config: &node_runtime_config
    working_directory: ~/work
    docker:
      - image: node:12.19-alpine

commands:
  yarn_install:
    steps:
      - restore_cache:
          keys:
            - nuxt-node-modules-v2-{{ checksum "yarn.lock" }}
      - run:
          command: |
            [ "`which yarn`" != "" ] && yarn || true
  save_node_module_cache:
    steps:
      - save_cache:
          key: nuxt-node-modules-v2-{{ checksum "yarn.lock" }}
          paths: node_modules

jobs:
  lint:
    <<: *node_runtime_config
    steps:
      - checkout
      - run:
          command: apk add --no-cache --update ca-certificates
      - yarn_install
      - run:
          command: yarn lint .
      - save_node_module_cache
  build:
    <<: *node_runtime_config
    steps:
      - checkout
      - run:
          command: apk add --no-cache --update ca-certificates
      - yarn_install
      - run:
          command: yarn build
      - save_node_module_cache

workflows:
  version: 2
  build:
    jobs:
      - lint
      - build
