version: 2.1

commands:
  yarn_install:
    steps:
      - restore_cache:
          keys:
            - nuxt-node-modules-v2-{{ checksum "yarn.lock" }}
      - run:
          command: |
            [ "`which yarn`" != "" ] && yarn || true
  save_node_module_cache:
    steps:
      - save_cache:
          key: nuxt-node-modules-v2-{{ checksum "yarn.lock" }}
          paths: node_modules

jobs:
  lint:
    working_directory: /home/circleci/project
    docker:
      - image: node:12.6-alpine
    steps:
      - checkout
      - run:
          name: install depend packages
          command: apk add --no-cache --update ca-certificates
      - yarn_install
      - run:
          command: yarn lint .
      - save_node_module_cache

  test:
    machine: true
    steps:
      - checkout
      - yarn_install
      - run:
          command: |
            LOCAL_UID=$(id -u $USER) LOCAL_GID=$(id -g $USER) \
            docker-compose -f docker-compose-circleci.yml run \
              -e user_password=$E2E_USER_PASSWORD -e user_email=$E2E_USER_EMAIL --rm puppeteer
      - save_node_module_cache

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
