version: 2.1

parameters:
  run_api_trigger_jobs:
    type: boolean
    default: false

commands:
  yarn_install:
    steps:
      - restore_cache:
          keys:
            - nuxt-node-modules-v2-{{ checksum "yarn.lock" }}
      - run:
          command: |
            [ "`which yarn`" != "" ] && yarn || true
  save_node_module_cache:
    steps:
      - save_cache:
          key: nuxt-node-modules-v2-{{ checksum "yarn.lock" }}
          paths: node_modules

jobs:
  lint:
    working_directory: /home/circleci/project
    docker:
      - image: node:12.6-alpine
    steps:
      - run: ':' # declared noop command because in order to use the conditional step need one or more tasks or the when statement
      - unless:
          condition: << pipeline.parameters.run_api_trigger_jobs >>
          steps:
            - checkout
            - run:
                name: install depend packages
                command: apk add --no-cache --update ca-certificates
            - yarn_install
            - run:
                command: yarn lint .
            - save_node_module_cache

  test:
    machine: true
    steps:
      - run: ':'
      - unless:
          condition: << pipeline.parameters.run_api_trigger_jobs >>
          steps:
            - checkout
            - yarn_install
            - run:
                name: jest
                command: |
                  TEST_ARGS="-i --silent --ci --coverage --reporters=jest-junit"
                  export TEST_ARGS

                  JEST_JUNIT_OUTPUT=reports/jest/results.xml \
                  LOCAL_UID=$(id -u $USER) LOCAL_GID=$(id -g $USER) \
                  docker-compose -f docker-compose-circleci.yml run --rm puppeteer
            - save_node_module_cache
            - store_test_results:
                path: reports

  something:
    docker:
      - image: node:12.6-alpine
    steps:
      - run: ':'
      - when:
          condition: << pipeline.parameters.run_api_trigger_jobs >>
          steps:
            - run: echo "run something"

workflows:
  build:
    jobs:
      - lint
      - test
  ## how to trigger bellow workflow
  # curl -u ${TOKEN}: --header 'Content-Type: application/json' -X POST -d '{"parameters": {"run_api_trigger_jobs": true}, "branch": "'${BRANCH}'"}' https://circleci.com/api/v2/project/gh/Yama-Tomo/vue-vuex-typescript-sample/pipeline
  trigger_api:
    jobs:
      - something
